# SUPEREZIO ENTERPRISE EDITION - CONFIGURATION FILE
# Configuração otimizada baseada nas melhores práticas 2025
# Autor: Marco Barreto + Claude Sonnet 4

[project]
# Identificação do projeto
name = "SUPEREZIO Enterprise Edition"
description = "Sistema Cognitivo de Automação Multi-Modal com IA Distribuída"
author = "Marco Barreto"
tags = ["AI", "Enterprise", "Automation", "Cognitive-Interface", "Multi-Modal"]
version = "6.0.0"

# Configurações de ambiente
user_env = []
session_timeout = 7200  # 2 horas
user_session_timeout = 86400  # 24 horas
cache = true

[UI]
# Interface customizations
name = "SUPEREZIO Enterprise"
show_readme_as_default = true
default_collapse_content = false
default_expand_messages = true
hide_cot = false

# CSS customization
custom_css = "/superezio.css"
custom_font = "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"

# Layout
default_sidebar_state = "open"
layout = "wide"

# Theme configuration
default_theme = "dark"

[UI.theme]
primary_color = "#00D4FF"      # Cyan enterprise
background_color = "#0A0A0A"   # Deep black
text_color = "#FFFFFF"         # Pure white
secondary_color = "#1E2A3A"    # Dark blue-gray
accent_color = "#7C3AED"       # Purple accent

[UI.theme.dark]
# Modo escuro otimizado
background = "#0A0A0A"
foreground = "#FFFFFF"
primary = "#00D4FF"
secondary = "#1E2A3A"
accent = "#7C3AED"
surface = "#1A1A1A"
on_surface = "#E0E0E0"

[UI.theme.light]  
# Modo claro (fallback)
background = "#FFFFFF"
foreground = "#0A0A0A"
primary = "#0066CC"
secondary = "#F5F5F5"
accent = "#6B46C1"

[features]
# Recursos enterprise habilitados
show_data_layer = false
multi_modal = true
speech_to_text = false
latex = true
unsafe_allow_html = true
edit_message = true

# Recursos avançados
streaming = true
auto_tag_thread = true
user_message_autoscroll = true

# Segurança
authentication_required = false
password_auth_callback = false

[tool]
# Configurações de ferramentas
enabled = true
max_iterations = 50
timeout = 300

[file]
# Configurações de arquivo
max_size_mb = 100
allowed_mime_types = [
    "text/plain",
    "text/markdown", 
    "text/csv",
    "application/json",
    "application/pdf",
    "image/jpeg",
    "image/png",
    "image/webp"
]
upload_timeout = 60

[chain_of_thought]
# Chain of thought configuration
mode = "full"  # hidden, tool_call, full
show_tool_calls = true
expand_by_default = true

[audio]
# Configurações de áudio
enabled = false
min_decibels = -45
initial_silence_timeout = 3000
silence_timeout = 1500
chunk_duration_ms = 1000
sample_rate = 44100

[copilot]
# Configurações para modo copilot
button_color = "#00D4FF"
button_hover_color = "#0099CC"
expand_button = true
chat_trigger = "SuperEzio"

[meta]
# Metadados
generated_by = "SUPEREZIO Enterprise v6.0.0"
charset = "UTF-8"
author = "Marco Barreto"
license = "Enterprise"
created_at = "2025-08-05"

# URLs e links
homepage = "https://superezio.enterprise"
documentation = "https://docs.superezio.enterprise"
support = "https://support.superezio.enterprise"

[telemetry]
# Telemetria e analytics
enabled = true
anonymous = true
collect_usage = true

[performance]
# Otimizações de performance
enable_compression = true
max_concurrent_requests = 100
request_timeout = 30
enable_http2 = true

# Memory management
max_memory_usage_mb = 2048
garbage_collection_threshold = 0.8

[logging]
# Configurações de logging enterprise
level = "INFO"
format = "json"
enable_correlation_ids = true
enable_performance_logging = true

# Rotação de logs
max_log_files = 10
max_log_size_mb = 50

[security]
# Configurações de segurança
enable_rate_limiting = true
rate_limit_requests_per_minute = 100
enable_input_sanitization = true
max_input_length = 10000

# CORS
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE"]
allowed_headers = ["*"]

[monitoring]
# Monitoramento e health checks
enable_health_checks = true
health_check_interval = 60
enable_metrics = true
metrics_port = 9090

[database]
# Configurações de banco (se necessário)
enabled = false
connection_string = ""
max_connections = 10
connection_timeout = 30

[redis]
# Configurações Redis (se necessário)
enabled = false
host = "localhost"
port = 6379
password = ""
db = 0

[deployment]
# Configurações de deployment
environment = "production"
debug = false
hot_reload = false
serve_static_files = true

# Network
host = "0.0.0.0"
port = 8000
max_workers = 4

[backup]
# Configurações de backup
enabled = true
interval_hours = 24
max_backups = 7
backup_location = "./backups"

[experimental]
# Recursos experimentais
websocket_compression = true
http3_support = false
advanced_caching = true
ai_model_optimization = true

[integrations]
# Integrações externas
openai_api_key = ""
anthropic_api_key = ""  
google_api_key = ""
azure_api_key = ""

# Webhook endpoints
webhook_url = ""
webhook_secret = ""

[advanced]
# Configurações avançadas
enable_custom_middleware = true
enable_request_preprocessing = true
enable_response_postprocessing = true
enable_custom_handlers = true

# Circuit breaker
circuit_breaker_failure_threshold = 5
circuit_breaker_recovery_timeout = 60

# Retry configuration
max_retries = 3
retry_backoff_multiplier = 2
retry_max_delay = 60